In [16]:
import numpy as np

# 1. Creo los 2 arrays con valores aleatorios

In [3]:
array1 = np.random.rand(3, 3)
array2 = np.random.rand(3, 3)

In [17]:
# Suma de array

suma = array1 + array2

In [18]:
# Resta de arrays

resta = array1 - array2

In [19]:
# Multiplicación de arrays

multiplicacion = array1 * array2

In [21]:
# División de arrays
# Se añade un pequeño valor para evitar división por cero

divisor = array2 + 0.0001
division = array1 / divisor

In [22]:
# Transpuesta de los arrays

transpuesta1 = array1.T
transpuesta2 = array2.T

In [23]:
# Determinante de los arrays

determinante1 = np.linalg.det(array1)
determinante2 = np.linalg.det(array2)

# 2. Crear un array de 100 elementos con valores del 1 al 100 y cambiar su forma a 10x10

In [11]:
array3 = np.arange(1, 101).reshape(10, 10)

In [24]:
# Extraer elementos en las posiciones impares

elementos_impares = array3[::2, ::2]


# 3. Generar un array de 1000 números aleatorios siguiendo una distribución normal


In [13]:
array4 = np.random.normal(size=1000)

In [25]:
# Calcular la media, mediana, desviación estándar y percentil 90 de los datos

media = np.mean(array4)
mediana = np.median(array4)
desviacion_estandar = np.std(array4)
percentil_90 = np.percentile(array4, 90)

# Imprimir resultados

In [15]:
print("Suma:\n", suma)
print("\nResta:\n", resta)
print("\nMultiplicación:\n", multiplicacion)
print("\nDivisión:\n", division)
print("\nTranspuesta 1:\n", transpuesta1)
print("\nTranspuesta 2:\n", transpuesta2)
print("\nDeterminante 1:", determinante1)
print("Determinante 2:", determinante2)
print("\nArray original:\n", array3)
print("\nElementos en posiciones impares:\n", elementos_impares)
print("\nMedia:", media)
print("Mediana:", mediana)
print("Desviación estándar:", desviacion_estandar)
print("Percentil 90:", percentil_90)

Suma:
 [[1.23629926 1.72869764 1.13419344]
 [1.49399095 0.59848422 0.9831915 ]
 [0.99473654 1.33875933 1.11331767]]

Resta:
 [[ 0.04617417  0.13558521 -0.6467797 ]
 [-0.12933738 -0.49473054  0.92482359]
 [ 0.20920766 -0.54938374 -0.24632978]]

Multiplicación:
 [[0.38157595 0.74250304 0.21701769]
 [0.5538202  0.02835626 0.02784171]
 [0.23643324 0.37261351 0.29469947]]

División:
 [[ 1.07741444  1.17006735  0.27364759]
 [ 0.84054805  0.09488959 32.57782323]
 [ 1.53226415  0.41802551  0.63756261]]

Transpuesta 1:
 [[0.64123672 0.68232678 0.6019721 ]
 [0.93214143 0.05187684 0.39468779]
 [0.24370687 0.95400754 0.43349395]]

Transpuesta 2:
 [[0.59506254 0.81166416 0.39276444]
 [0.79655621 0.54660738 0.94407154]
 [0.89048657 0.02918396 0.67982373]]

Determinante 1: 0.09059601452673378
Determinante 2: 0.265503657237378

Array original:
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37 